server:
  port: 9000

spring:
  datasource:
    platform: postgresql
    username: postgres
    password: postgres123
    url: jdbc:postgresql://127.0.0.1:5432/training
    driver-class-name: org.postgresql.Driver   
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true    
  autoconfigure:
    exclude:
  #  - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration